name: Automatic checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: pylint
      run: pylint ${{github.workspace}}/src/ecap5_treq
  documentation:
    runs-on: self-hosted
    env:
      VENV_NAME: ${{github.run_number}}-${{github.run_attempt}}

    steps:
    - uses: actions/checkout@v3

    - name: Setup python virtual environment
      run: >-
        cd ${{github.workspace}} &&
        python3 -m venv ${{ env.VENV_NAME }}

    - name: Install dependencies
      run: >-
        source ${{github.workspace}}/${{ env.VENV_NAME }}/bin/activate &&
        pip install ${{github.workspace}} &&
        echo "${{github.workspace}}/${{ env.VENV_NAME }}/bin" >> $GITHUB_PATH

    - name: Generate documentation
      run: make -C ${{github.workspace}}/docs/ html

    - uses: actions/upload-pages-artifact@v2
      with: 
        name: ecap5-treq-documentation
        path: ${{github.workspace}}/docs/build/html
    
    - uses: actions/deploy-pages@v4
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        artifact_name: ecap5-treq_documentation
        preview: true
