name: Automatic checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCUMENTATION_ARTIFACT_NAME: ecap5-treq-documentation-${{github.run_number}}-${{github.run_attempt}}
  COVERAGE_REPORT_ARTIFACT_NAME: ecap5-treq-coverage-${{github.run_number}}-${{github.run_attempt}}

jobs:
  prepare:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Restore cache
      id: cache-dependencies-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ github.workspace }}/venv
        key: venv-${{ hashFiles('pyproject.toml') }}
        lookup-only: true

    - name: Setup python virtual environment
      if: ${{ steps.cache-dependencies-restore.outputs.cache-hit != 'true' }}
      run: >-
        cd ${{github.workspace}} &&
        python3 -m venv venv

    - name: Install dependencies
      if: ${{ steps.cache-dependencies-restore.outputs.cache-hit != 'true' }}
      run: >-
        source ${{github.workspace}}/venv/bin/activate &&
        pip install ${{github.workspace}} &&
        echo "${{github.workspace}}/venv/bin" >> $GITHUB_PATH

    - name: Save cache
      id: cache-dependencies-save
      if: ${{ steps.cache-dependencies-restore.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v3
      with:
        path: ${{ github.workspace }}/venv
        key: venv-${{ hashFiles('pyproject.toml') }}

  lint:
    runs-on: self-hosted
    needs: prepare

    steps:
    - uses: actions/checkout@v3

    - name: Restore cache
      id: cache-dependencies-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ github.workspace }}/venv
        key: venv-${{ hashFiles('pyproject.toml') }}

    - name: Add dependencies to PATH
      run: echo "${{github.workspace}}/venv/bin" >> $GITHUB_PATH

    - name: pylint
      run: >-
        source ${{github.workspace}}/venv/bin/activate &&
        pylint ${{github.workspace}}/src/ecap5_treq --rcfile="${{github.workspace}}/.pylintrc"

  tests:
    runs-on: self-hosted
    needs: lint

    steps:
    - uses: actions/checkout@v3

    - name: Restore cache
      id: cache-dependencies-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ github.workspace }}/venv
        key: venv-${{ hashFiles('pyproject.toml') }}

    - name: Add dependencies to PATH
      run: echo "${{github.workspace}}/venv/bin" >> $GITHUB_PATH

    - name: Run unit tests
      run: >-
        source ${{github.workspace}}/venv/bin/activate &&
        pytest --pyargs ${{github.workspace}}/src/ecap5_treq -vv --cov=src/ecap5_treq

    - name: Save coverage data in cache
      id: cache-coverage-data-save
      uses: actions/cache/save@v3
      with:
        path: ${{ github.workspace }}/.coverage
        key: coverage-data-${{github.run_id}}-${{github.run_attempt}}

  coverage:
    runs-on: self-hosted
    needs: tests

    steps:
    - uses: actions/checkout@v3

    - name: Restore cache
      id: cache-dependencies-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ github.workspace }}/venv
        key: venv-${{ hashFiles('pyproject.toml') }}

    - name: Add dependencies to PATH
      run: echo "${{github.workspace}}/venv/bin" >> $GITHUB_PATH

    - name: Restore cached coverage data
      id: cache-coverage-data-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ github.workspace }}/.coverage
        key: coverage-data-${{github.run_id}}-${{github.run_attempt}}

    - name: Code coverage
      id: code-coverage
      run: >-
        source ${{github.workspace}}/venv/bin/activate &&
        coverage html --fail-under=100

    - name: Upload coverage report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.COVERAGE_REPORT_ARTIFACT_NAME}}
        path: ${{github.workspace}}/htmlcov

  documentation:
    runs-on: self-hosted
    needs: prepare

    steps:
    - uses: actions/checkout@v3

    - name: Restore cache
      id: cache-dependencies-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ github.workspace }}/venv
        key: venv-${{ hashFiles('pyproject.toml') }}

    - name: Add dependencies to PATH
      run: echo "${{github.workspace}}/venv/bin" >> $GITHUB_PATH

    - name: Generate documentation
      run: make -C ${{github.workspace}}/docs/ html

    - uses: actions/upload-pages-artifact@v2
      with: 
        name: ${{env.DOCUMENTATION_ARTIFACT_NAME}}
        path: ${{github.workspace}}/docs/build/html

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: self-hosted

    needs: documentation

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/deploy-pages@v2
      id: deployment
      with:
        artifact_name: ${{env.DOCUMENTATION_ARTIFACT_NAME}}
        preview: true
