name: Automatic checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCUMENTATION_ARTIFACT_NAME: ecap5-treq-documentation-${{github.run_number}}-${{github.run_attempt}}

jobs:
  prepare:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Check if cache key exists
      id: check-if-cache
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        KEY=venv-${{ hashFiles('pyproject.toml') }}
        CACHE_HIT=$(gh actions-cache list --key $KEY | grep -q $KEY && echo -n 'true' || echo -n 'false')
        echo "cache-hit=$CACHE_HIT" >> $GITHUB_OUTPUT

    - name: Setup python virtual environment
      if: ${{ steps.check-if-cache.outputs.cache-hit != 'true' }}
      run: >-
        cd ${{github.workspace}} &&
        python3 -m venv venv

    - name: Install dependencies
      if: ${{ steps.check-if-cache.outputs.cache-hit != 'true' }}
      run: >-
        source ${{github.workspace}}/venv/bin/activate &&
        pip install ${{github.workspace}} &&
        echo "${{github.workspace}}/venv/bin" >> $GITHUB_PATH

    - name: Save cache
      id: cache-dependencies-save
      if: ${{ steps.check-if-cache.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v3
      with:
        path: ${{ github.workspace }}/venv
        key: venv-${{ hashFiles('pyproject.toml') }}

  lint:
    runs-on: self-hosted
    needs: prepare

    steps:
    - uses: actions/checkout@v3

    - name: Restore cache
      id: cache-dependencies-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ github.workspace }}/venv
        key: venv-${{ hashFiles('pyproject.toml') }}

    - name: Add dependencies to PATH
      run: echo "${{github.workspace}}/venv/bin" >> $GITHUB_PATH

    - name: pylint
      run: >-
        source ${{github.workspace}}/venv/bin/activate &&
        pylint ${{github.workspace}}/src/ecap5_treq --rcfile="${{github.workspace}}/.pylintrc"

  tests:
    runs-on: self-hosted
    needs: lint

    steps:
    - uses: actions/checkout@v3

    - name: Restore cache
      id: cache-dependencies-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ github.workspace }}/venv
        key: venv-${{ hashFiles('pyproject.toml') }}

    - name: Add dependencies to PATH
      run: echo "${{github.workspace}}/venv/bin" >> $GITHUB_PATH

    - name: Run unit tests
      run: >-
        source ${{github.workspace}}/venv/bin/activate &&
        pytest --pyargs ${{github.workspace}}/src/ecap5_treq -vv

  documentation:
    runs-on: self-hosted
    needs: prepare

    steps:
    - uses: actions/checkout@v3

    - name: Restore cache
      id: cache-dependencies-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ github.workspace }}/venv
        key: venv-${{ hashFiles('pyproject.toml') }}

    - name: Add dependencies to PATH
      run: echo "${{github.workspace}}/venv/bin" >> $GITHUB_PATH

    - name: Generate documentation
      run: make -C ${{github.workspace}}/docs/ html

    - uses: actions/upload-pages-artifact@v2
      with: 
        name: ${{env.DOCUMENTATION_ARTIFACT_NAME}}
        path: ${{github.workspace}}/docs/build/html

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: self-hosted

    needs: documentation

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/deploy-pages@v2
      id: deployment
      with:
        artifact_name: ${{env.DOCUMENTATION_ARTIFACT_NAME}}
        preview: true
