name: Automatic checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: pylint
      run: pylint ${{github.workspace}}/src/ecap5_treq
  documentation:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Install the dependencies
      run: >-
        mkdir -p ${{github.workspace}}/_deps/bin &&
        pip install . --target ${{github.workspace}}/_deps --install-option="--install-scripts=${{github.workspace}}/_deps/bin" &&
        echo "${{github.workspace}}/_deps/bin" >> $GITHUB_PATH

    - name: Generate documentation
      run: make -C ${{github.workspace}}/docs/ html

    - uses: actions/upload-pages-artifact@v2
      with: 
        name: ecap5-treq-documentation
        path: ${{github.workspace}}/docs/build/html
    
    - uses: actions/deploy-pages@v4
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        artifact_name: ecap5-treq_documentation
        preview: true
     
