name: Automatic checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCUMENTATION_ARTIFACT_NAME: ecap5-treq-documentation-${{github.run_number}}-${{github.run_attempt}}
  VENV_NAME: ${{github.run_number}}-${{github.run_attempt}}

jobs:
  lint:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Setup python virtual environment
      run: >-
        cd ${{github.workspace}} &&
        python3 -m venv ${{ env.VENV_NAME }}

    - name: Install dependencies
      run: >-
        source ${{github.workspace}}/${{ env.VENV_NAME }}/bin/activate &&
        pip install ${{github.workspace}} &&
        echo "${{github.workspace}}/${{ env.VENV_NAME }}/bin" >> $GITHUB_PATH

    - name: pylint
      run: >-
        source ${{github.workspace}}/${{ env.VENV_NAME }}/bin/activate &&
        pylint ${{github.workspace}}/src/ecap5_treq --rcfile="${{github.workspace}}/.pylintrc"

  tests:
    runs-on: self-hosted

    needs: lint

    steps:
    - uses: actions/checkout@v3

    - name: Setup python virtual environment
      run: >-
        cd ${{github.workspace}} &&
        python3 -m venv ${{ env.VENV_NAME }}

    - name: Install dependencies
      run: >-
        source ${{github.workspace}}/${{ env.VENV_NAME }}/bin/activate &&
        pip install ${{github.workspace}} &&
        echo "${{github.workspace}}/${{ env.VENV_NAME }}/bin" >> $GITHUB_PATH

    - name: Run unit tests
      run: >-
        source ${{github.workspace}}/${{ env.VENV_NAME }}/bin/activate &&
        pytest --pyargs ${{github.workspace}}/src/ecap5_treq

  documentation:
    runs-on: self-hosted

    env:
      VENV_NAME: ${{github.run_number}}-${{github.run_attempt}}

    steps:
    - uses: actions/checkout@v3

    - name: Setup python virtual environment
      run: >-
        cd ${{github.workspace}} &&
        python3 -m venv ${{ env.VENV_NAME }}

    - name: Install dependencies
      run: >-
        source ${{github.workspace}}/${{ env.VENV_NAME }}/bin/activate &&
        pip install ${{github.workspace}} &&
        echo "${{github.workspace}}/${{ env.VENV_NAME }}/bin" >> $GITHUB_PATH

    - name: Generate documentation
      run: make -C ${{github.workspace}}/docs/ html

    - uses: actions/upload-pages-artifact@v2
      with: 
        name: ${{env.DOCUMENTATION_ARTIFACT_NAME}}
        path: ${{github.workspace}}/docs/build/html

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: self-hosted

    needs: documentation

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/deploy-pages@v2
      id: deployment
      with:
        artifact_name: ${{env.DOCUMENTATION_ARTIFACT_NAME}}
        preview: true
